export RESTIC_REPOSITORY="REPLACE_WITH_S3_OR_B2_BUCKET_URL" #s3:https://s3.amazonaws.com/bucketname
export RESTIC_PASSWORD="REPLACE_WITH_RESTIC_REPOSITORY_PASSWORD"

export AWS_ACCESS_KEY_ID="REPLACE_WITH_AWS_ACCESS_KEY"
export AWS_SECRET_ACCESS_KEY="REPLACE_WITH_AWS_SECRET_ACCESS_KEY"

export B2_ACCOUNT_ID="REPLACE_WITH_B2_ACCOUNT_ID"
export B2_ACCOUNT_KEY="REPLACE_WITH_B2_ACCOUNT_KEY"

export TELEGRAM_TOKEN="REPLACE_WITH_TELEGRAM_TOKEN"
export CHAT_ID="REPLACE_WITH_TELEGRAM_CHAT_ID"
